### ISSUE TITLE
Afficher le nombre de cartes dans le tas

### ISSUE THREAD

**Issue by paranoidduck** [seventh/FlammeRouge#4]
Pour la stratégie.

**Comment by seventh** [comment]
Les cartes jouées plutôt, non ? Toute la question c'est de savoir jusqu'à quel point on assiste le joueur, entre ce qu'il a le droit de faire avec la vraie boîte, et ce qu'on peut lui offrir.

Typiquement, sur TricTrac, monsieur Guillaume met devant lui les cartes jouées, ce qui lui permet de savoir ce qu'il lui reste (plus les fatigues).

**Comment by seventh** [comment]
Fermé, au profit de https://github.com/seventh/FlammeRouge/issues/9
