### ISSUE TITLE
Misère d'énergie

### ISSUE THREAD

**Issue by seventh** [seventh/FlammeRouge#7]
Les règles ne le prévoient pas, mais un coureur peut se retrouver sans plus aucune carte dans son tas.

Ce qui est dit :+1: 
  «If there are fewer than four cards total in your energy deck (recycled & face down), simply draw all cards.»

Ce qui laisse penser qu'un coureur sans carte passe son tour... jusqu'à ce qu'il engrange de la fatigue, ce qui n'est pas très cohérent.

Je propose qu'un coureur sans carte ait d'office une carte fatigue (2).

**Comment by paranoidduck** [comment]
Ça me paraît une solution raisonnable

**Comment by seventh** [comment]
Corrigé à l'altération 3317e4c99128331543e604141a63f4f2ea14bae6
